CREATE SCHEMA IF NOT EXISTS todolist DEFAULT CHARACTER SET utf8 ;
USE todolist;

CREATE TABLE IF NOT EXISTS todo (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB;
