server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        package-scan: com.javaguru
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: liquibase-changeLog.xml
logging:
  level:
    com.javaguru: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
      base-path: /